<?php

namespace App;

use App\Traits\Searchable;
use Carbon\Carbon;
use Jenssegers\Mongodb\Eloquent\Model as Model;
use Jenssegers\Mongodb\Eloquent\HybridRelations;

class Task extends Model
{
    use HybridRelations;
    use Searchable;

    protected $connection = 'archive';
    protected $collection = 'tasks';
    protected $searchableColumns = ['tweet_text', 'user_id', 'user_screen_name', 'json'];
    protected $searchableRelations = [];
    public function save(array $options = [])
    {
        \Log::info('Creating Task');
        return parent::save($options); // TODO: Change the autogenerated stub
    }

}
