<?php

namespace App;

use OauthPhirehose;
use App\Jobs\ProcessTweet;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Protestwit\Group\Models\Group;

class TwitterStream extends OauthPhirehose
{
    use DispatchesJobs;
    
    protected $group;
    protected $io_type; //Send or Receive

    /**
    * Enqueue each status
    *
    * @param string $status
    */
    public function enqueueStatus($status)
    {
        $this->dispatch(new ProcessTweet($status,$this->getTrack()));
    }
    
    
    public function setTrack(array $trackWords)
    {
        \Log::info($trackWords);
        parent::setTrack($trackWords); // TODO: Change the autogenerated stub
    }


    public function setGroup(Group $group)
    {
        $this->group = $group;
        return $this;
    }
    
}
